development:
  adapter: postgresql
  encoding: unicode
  database: barterville_development
  pool: 5
  host: localhost
  username: postgres
  password: 

  production:
  adapter: postgresql
  encoding: unicode
  database: barterville_production
  pool: 5
  host: localhost
  username: postgres
  password: 